import jsPDF from 'jspdf';
import type { Analysis } from '../types/models';

export function exportAnalysisToPDF(analysis: Analysis) {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  let yPosition = 20;
  const margin = 20;
  const lineHeight = 7;

  // Helper function to add text with word wrap
  const addWrappedText = (text: string, y: number, maxWidth: number = pageWidth - 2 * margin) => {
    const lines = pdf.splitTextToSize(text, maxWidth);
    pdf.text(lines, margin, y);
    return y + (lines.length * lineHeight);
  };

  // Add watermark
  pdf.setTextColor(200, 200, 200);
  pdf.setFontSize(40);
  pdf.text('Plus+ Talent', pageWidth/2, pdf.internal.pageSize.getHeight()/2, {
    align: 'center',
    angle: 45
  });

  // Reset text color and font size for content
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(20);
  pdf.text('Analysis Report', margin, yPosition);

  // Basic information
  yPosition += 15;
  pdf.setFontSize(12);
  pdf.text('Date: ' + new Date(analysis.created_at).toLocaleDateString(), margin, yPosition);

  // Fit Score
  yPosition += 15;
  pdf.setFontSize(16);
  pdf.text('Fit Score: ' + analysis.fit_score + '/10', margin, yPosition);

  // Verdict
  yPosition += 10;
  pdf.text('Verdict: ' + analysis.verdict.replace('_', ' '), margin, yPosition);

  // Reasoning
  yPosition += 15;
  pdf.setFontSize(14);
  pdf.text('Key Findings:', margin, yPosition);
  yPosition += 7;
  pdf.setFontSize(12);
  analysis.reasoning.forEach(reason => {
    yPosition = addWrappedText('• ' + reason, yPosition);
    yPosition += 3;
  });

  // Suggestions
  yPosition += 10;
  pdf.setFontSize(14);
  pdf.text('Improvement Suggestions:', margin, yPosition);
  yPosition += 7;
  pdf.setFontSize(12);
  analysis.suggestions.forEach(suggestion => {
    yPosition = addWrappedText('• ' + suggestion, yPosition);
    yPosition += 3;
  });

  // Interview Plan
  yPosition += 10;
  pdf.setFontSize(14);
  pdf.text('Interview Plan:', margin, yPosition);
  yPosition += 7;
  pdf.setFontSize(12);
  yPosition = addWrappedText(analysis.interview_plan, yPosition);

  // Add footer
  pdf.setFontSize(10);
  pdf.setTextColor(128, 128, 128);
  const footer = 'Generated by Plus+ Talent CV Analyzer';
  pdf.text(footer, pageWidth/2, pdf.internal.pageSize.getHeight() - 10, { align: 'center' });

  // Save the PDF
  const filename = 'analysis-' + new Date().toISOString().split('T')[0] + '.pdf';
  pdf.save(filename);
}